//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBiblioteca.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanciones
    {
        public int ID_Sancion { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public string Motivo { get; set; }
        public Nullable<System.DateTime> FechaSancion { get; set; }
        public Nullable<System.DateTime> FechaFinSancion { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
